// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqqwcH20i8g3xdvMDF6cpckEn702NcRns',
    appId: '1:682847052554:web:4073abc27bc78cb8b390f3',
    messagingSenderId: '682847052554',
    projectId: 'fluxolog-1dc54',
    authDomain: 'fluxolog-1dc54.firebaseapp.com',
    storageBucket: 'fluxolog-1dc54.firebasestorage.app',
    measurementId: 'G-TXCZ9GQT6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMMcpseGVWMR9jl8P2McXbCE-v5khXrGw',
    appId: '1:682847052554:android:2b5cb2e6c31e40b7b390f3',
    messagingSenderId: '682847052554',
    projectId: 'fluxolog-1dc54',
    storageBucket: 'fluxolog-1dc54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2IhXyqZ4gKFhxyq-O2JlAqtwcTkT5IaM',
    appId: '1:682847052554:ios:39d2ee3a92077943b390f3',
    messagingSenderId: '682847052554',
    projectId: 'fluxolog-1dc54',
    storageBucket: 'fluxolog-1dc54.firebasestorage.app',
    iosBundleId: 'com.example.fluxo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2IhXyqZ4gKFhxyq-O2JlAqtwcTkT5IaM',
    appId: '1:682847052554:ios:39d2ee3a92077943b390f3',
    messagingSenderId: '682847052554',
    projectId: 'fluxolog-1dc54',
    storageBucket: 'fluxolog-1dc54.firebasestorage.app',
    iosBundleId: 'com.example.fluxo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqqwcH20i8g3xdvMDF6cpckEn702NcRns',
    appId: '1:682847052554:web:d0e278aaa8af6c57b390f3',
    messagingSenderId: '682847052554',
    projectId: 'fluxolog-1dc54',
    authDomain: 'fluxolog-1dc54.firebaseapp.com',
    storageBucket: 'fluxolog-1dc54.firebasestorage.app',
    measurementId: 'G-ZGTKXS5M9N',
  );
}